In [1]:
# Pandas is a open source library, used for Data Structure

In [2]:
# importing libraries

import numpy as np
import pandas as pd

In [3]:
labels = ['a','b','c']

In [4]:
labels

['a', 'b', 'c']

In [5]:
my_data = [10,20,30]

In [6]:
my_data

[10, 20, 30]

In [8]:
arr = np.array([50,60,70])

In [9]:
arr

array([50, 60, 70])

In [10]:
# dictionaries
d ={'x':80,'y':90,'z':50}

In [11]:
d

{'x': 80, 'y': 90, 'z': 50}

In [13]:
# Series are 1 dimensional

ser1 = pd.Series(data=my_data)

In [15]:
ser1

0    10
1    20
2    30
dtype: int64

In [16]:
type(ser1)

pandas.core.series.Series

In [19]:
ser1

0    10
1    20
2    30
dtype: int64

In [20]:
ser2 =pd.Series(data=my_data,index=labels)

In [21]:
ser2

a    10
b    20
c    30
dtype: int64

In [22]:
ser3 = pd.Series(data=arr)

In [23]:
ser3

0    50
1    60
2    70
dtype: int32

In [24]:
ser4 =pd.Series(d)

In [25]:
ser4

x    80
y    90
z    50
dtype: int64

In [26]:
ser5 =pd.Series([10,20,30,40,50])

In [27]:
ser5

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [28]:
# Dataframes are 2D (rows,columns)

In [29]:
np.random.rand(2)

array([0.16190203, 0.97868306])

In [30]:
np.random.rand(2,1)

array([[0.66180968],
       [0.9395947 ]])

In [31]:
np.random.rand(2,2)

array([[0.00908736, 0.317848  ],
       [0.30778494, 0.85999936]])

In [32]:
np.random.rand(5,1)

array([[0.25389246],
       [0.53363555],
       [0.51561835],
       [0.95973385],
       [0.62841279]])

In [33]:
np.random.rand(5,6)

array([[0.8739192 , 0.89775794, 0.36673043, 0.42868097, 0.40683788,
        0.875338  ],
       [0.285195  , 0.17541249, 0.57672661, 0.7711274 , 0.35089081,
        0.50636325],
       [0.28127184, 0.79581738, 0.65899444, 0.3547234 , 0.34189369,
        0.93509838],
       [0.87417053, 0.01774672, 0.71906483, 0.82797136, 0.35484466,
        0.37731106],
       [0.57856109, 0.01944838, 0.93170977, 0.52095887, 0.5591122 ,
        0.5393365 ]])

In [34]:
np.random.rand(3,4)

array([[0.13482686, 0.60531841, 0.93364161, 0.43640116],
       [0.45495052, 0.93294535, 0.39435631, 0.49283812],
       [0.13745134, 0.60163673, 0.12105012, 0.12122497]])

In [35]:
df =pd.DataFrame(np.random.rand(5,4))

In [36]:
df

0         1         2         3
0  0.987135  0.913239  0.665351  0.682191
1  0.001142  0.462617  0.901907  0.838508
2  0.184595  0.599866  0.369625  0.661417
3  0.161397  0.530607  0.594128  0.264383
4  0.357020  0.814967  0.993498  0.997930

In [38]:
df = pd.DataFrame(np.random.rand(5,4),columns=['amit','priyali','pranali','rajat'])

In [39]:
df

amit   priyali   pranali     rajat
0  0.525127  0.166887  0.226369  0.041727
1  0.809799  0.050144  0.632726  0.138393
2  0.490751  0.297985  0.124797  0.343482
3  0.200577  0.901302  0.620145  0.209857
4  0.782663  0.934342  0.115683  0.900204

In [41]:
df = pd.DataFrame(np.random.rand(5,4),columns=['amit','priyali','pranali','rajat'],index=['u','t','l','p','i'])

In [42]:
df1 = pd.DataFrame(np.random.rand(3,2))

In [43]:
df1

0         1
0  0.098960  0.408026
1  0.134048  0.602266
2  0.360636  0.966643

In [44]:
# revert columns

In [45]:
df['amit']

u    0.606786
t    0.918122
l    0.195099
p    0.478036
i    0.286435
Name: amit, dtype: float64

In [46]:
df[['priyali','pranali']]

priyali   pranali
u  0.635979  0.593051
t  0.620106  0.876047
l  0.126947  0.927014
p  0.455183  0.132766
i  0.326792  0.064754

In [47]:
df['rachna'] = [45,56,78,3,6]

In [48]:
df

amit   priyali   pranali     rajat  rachna
u  0.606786  0.635979  0.593051  0.442918      45
t  0.918122  0.620106  0.876047  0.219499      56
l  0.195099  0.126947  0.927014  0.572037      78
p  0.478036  0.455183  0.132766  0.829958       3
i  0.286435  0.326792  0.064754  0.253604       6

In [51]:
df.shape

(5, 5)

In [54]:
df['new'] = ['r','y','u','p','t']

In [55]:
df

amit   priyali   pranali     rajat  rachna new
u  0.606786  0.635979  0.593051  0.442918      45   r
t  0.918122  0.620106  0.876047  0.219499      56   y
l  0.195099  0.126947  0.927014  0.572037      78   u
p  0.478036  0.455183  0.132766  0.829958       3   p
i  0.286435  0.326792  0.064754  0.253604       6   t

In [52]:
# drop

In [56]:
# row ----> (axis = 0), columns ----> (axis=1)
df.drop('new',axis=1) 

amit   priyali   pranali     rajat  rachna
u  0.606786  0.635979  0.593051  0.442918      45
t  0.918122  0.620106  0.876047  0.219499      56
l  0.195099  0.126947  0.927014  0.572037      78
p  0.478036  0.455183  0.132766  0.829958       3
i  0.286435  0.326792  0.064754  0.253604       6

In [57]:
df.shape

(5, 6)

In [58]:
df.drop('new',axis=1,inplace=True)

In [59]:
df

amit   priyali   pranali     rajat  rachna
u  0.606786  0.635979  0.593051  0.442918      45
t  0.918122  0.620106  0.876047  0.219499      56
l  0.195099  0.126947  0.927014  0.572037      78
p  0.478036  0.455183  0.132766  0.829958       3
i  0.286435  0.326792  0.064754  0.253604       6

In [61]:
df.drop('rachna',axis=1)

amit   priyali   pranali     rajat
u  0.606786  0.635979  0.593051  0.442918
t  0.918122  0.620106  0.876047  0.219499
l  0.195099  0.126947  0.927014  0.572037
p  0.478036  0.455183  0.132766  0.829958
i  0.286435  0.326792  0.064754  0.253604

In [62]:
df

amit   priyali   pranali     rajat  rachna
u  0.606786  0.635979  0.593051  0.442918      45
t  0.918122  0.620106  0.876047  0.219499      56
l  0.195099  0.126947  0.927014  0.572037      78
p  0.478036  0.455183  0.132766  0.829958       3
i  0.286435  0.326792  0.064754  0.253604       6

In [63]:
df.drop('rachna',axis=1,inplace=True)

In [64]:
df

amit   priyali   pranali     rajat
u  0.606786  0.635979  0.593051  0.442918
t  0.918122  0.620106  0.876047  0.219499
l  0.195099  0.126947  0.927014  0.572037
p  0.478036  0.455183  0.132766  0.829958
i  0.286435  0.326792  0.064754  0.253604

In [65]:
df3 = pd.read_csv('sat.csv')

In [66]:
df3

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [67]:
df4 = pd.read_csv('sat.csv')

In [69]:
df4

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]